### ISSUE TITLE
Debian package: RFE: Do not overwrite local.json by default

### ISSUE THREAD

**Issue by adriangibanelbtactic** [ONLYOFFICE/document-server-package#235] opened 2022-01-24 17:46 UTC
**Describe your problem**

When you upgrade onlyoffice-documentserver package it overwrites `/etc/onlyoffice/documentserver/local.json` file every time with its default contents.

**About JWT_SECRET**

Please note that I am already aware about the official way of dealing with local.json being overwritten when you upgrade the onlyoffice-documentserver package that it's explained at the [Installing ONLYOFFICE Docs Community Edition for Debian, Ubuntu, and derivatives](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx) page. Those are the JWT options.

**Request**
At our installations we modify more stuff in that file than the JWT_SECRET.

What I request is what happens in most usual Debian packages. You define the local.json file as a conf file that your final user can modify in your package definition.

So when the package is updated if the user has modified that file a message similar to following one is asked to the final user.

```
Configuration file '/etc/onlyoffice/documentserver/local.json'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** local.json (Y/I/N/O/D/Z) [default=N] ? N
```

Thank you very much!

**Comment by ShockwaveNN** [comment] 2022-01-25 07:32
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/892

I know your issue is better placed in this repo but at times of 892 - this repo was private

**Comment by adriangibanelbtactic** [comment] 2022-01-25 09:21
> I think it's a duplicate of [ONLYOFFICE/DocumentServer#892](https://github.com/ONLYOFFICE/DocumentServer/issues/892)
> 
> I know your issue is better placed in this repo but at times of 892 - this repo was private

In that case I advise you to close that other issue while pointing people to check this issue instead. This is the place where to fix it properly, in the package definition.

**Comment by ShockwaveNN** [comment] 2022-01-25 09:26
Done moving, I think we can close this one

**Closed by ShockwaveNN** 2022-01-25 09:26 UTC
